# Generated by Django 4.1.7 on 2023-04-30 14:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="machine",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(default="PC", max_length=15)),
                (
                    "ip",
                    models.CharField(
                        default="172.0.0.1",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.?\\b){4}$"
                            )
                        ],
                    ),
                ),
                ("etat", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="personnel",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("login", models.CharField(max_length=20)),
                (
                    "password",
                    models.CharField(
                        default="9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator("^[a-z0-9]{64}$")
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="infrastructure",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=20)),
                ("pays", models.CharField(max_length=30)),
                ("ville", models.CharField(max_length=64)),
                (
                    "coordonnees",
                    models.CharField(
                        max_length=18,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?),\\s*[-+]?([1-9]?\\d(\\.\\d+)?|1[0-7]\\d(\\.\\d+)?|180(\\.0+)?)$"
                            )
                        ],
                    ),
                ),
                (
                    "id_machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="RT_app.machine"
                    ),
                ),
                (
                    "id_personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RT_app.personnel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="entretien",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=15)),
                ("description", models.TextField()),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(2023, 4, 30, 14, 39, 35, 945062)
                    ),
                ),
                (
                    "id_personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RT_app.personnel",
                    ),
                ),
            ],
        ),
    ]
