# Generated by Django 4.1.7 on 2023-05-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="id_infrastructure",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="RT_app.infrastructure",
            ),
        ),
    ]
