# Generated by Django 4.1.7 on 2023-06-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0002_alter_personnel_id_infrastructure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(default="2023-06-08"),
        ),
        migrations.AlterField(
            model_name="entretien",
            name="nom",
            field=models.CharField(default="Mise à jour", max_length=50),
        ),
    ]
