# Generated by Django 4.1.7 on 2023-04-30 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0002_alter_entretien_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 30, 15, 15, 3, 89310)
            ),
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="id_machine",
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="id_machine",
            field=models.ManyToManyField(to="RT_app.machine"),
        ),
    ]
