# Generated by Django 4.1.7 on 2023-04-30 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0004_alter_entretien_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 30, 15, 35, 55, 665715)
            ),
        ),
        migrations.AlterField(
            model_name="entretien",
            name="type",
            field=models.CharField(
                choices=[
                    ("PREVENTIF", "Préventif"),
                    ("CORRECTIF", "Correctif"),
                    ("AMELIORATION", "Amélioration"),
                    ("MISE A JOUR", "Mise à jour"),
                    ("REPARATION", "Réparation"),
                    ("AUTRE", "Autre"),
                ],
                default="PREVENTIF",
                max_length=15,
            ),
        ),
    ]
