# Generated by Django 4.1.7 on 2023-04-30 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0005_alter_entretien_date_alter_entretien_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entretien",
            name="id_machine",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="RT_app.machine",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 30, 15, 37, 13, 657152)
            ),
        ),
    ]
