# Generated by Django 4.1.7 on 2023-04-30 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0006_entretien_id_machine_alter_entretien_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 30, 15, 37, 53, 791966)
            ),
        ),
    ]
