# Generated by Django 4.1.7 on 2023-04-30 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0010_alter_entretien_date_alter_infrastructure_id_machine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="machine",
            old_name="infra",
            new_name="id_infrastructure",
        ),
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 30, 16, 21, 20, 704780)
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="id_machine",
            field=models.ManyToManyField(
                limit_choices_to={
                    "id_infrastructure": models.AutoField(
                        editable=False, primary_key=True, serialize=False
                    )
                },
                to="RT_app.machine",
            ),
        ),
    ]
