# Generated by Django 4.1.7 on 2023-04-30 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0012_alter_entretien_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infrastructure",
            name="id_machine",
        ),
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 30, 16, 39, 51, 211104)
            ),
        ),
    ]
