# Generated by Django 4.1.7 on 2023-04-30 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0013_remove_infrastructure_id_machine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entretien",
            name="fait",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 30, 17, 51, 35, 855470)
            ),
        ),
    ]
