# Generated by Django 4.1.7 on 2023-04-30 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0014_entretien_fait_alter_entretien_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entretien",
            old_name="fait",
            new_name="etat",
        ),
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 30, 18, 25, 23, 825500)
            ),
        ),
    ]
