# Generated by Django 4.1.7 on 2023-05-07 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0015_rename_fait_entretien_etat_alter_entretien_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="type_machine",
            field=models.CharField(
                choices=[
                    ("PC", "PC - OS windows"),
                    ("Mac", "Mac - OS MacOS"),
                    ("Serveur", "Serveur - OS Debian"),
                    ("Autre", "Autre type de machine"),
                ],
                default="PC",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 7, 17, 1, 51, 706736)
            ),
        ),
    ]
