# Generated by Django 4.1.7 on 2023-05-07 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0016_machine_type_machine_alter_entretien_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 7, 17, 6, 41, 691214)
            ),
        ),
        migrations.CreateModel(
            name="entretien_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_entretien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RT_app.entretien",
                    ),
                ),
                (
                    "id_machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="RT_app.machine"
                    ),
                ),
            ],
        ),
    ]
