# Generated by Django 4.1.7 on 2023-05-07 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0017_alter_entretien_date_entretien_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 7, 20, 59, 8, 556030)
            ),
        ),
    ]
