# Generated by Django 4.1.7 on 2023-05-12 11:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0018_alter_entretien_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 12, 11, 36, 45, 10926)
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="coordonnees",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?)\\s*[-+]?([1-9]?\\d(\\.\\d+)?|1[0-7]\\d(\\.\\d+)?|180(\\.0+)?)$"
                    )
                ],
            ),
        ),
    ]
