# Generated by Django 4.1.7 on 2023-05-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0019_alter_entretien_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(default="2023-05-12"),
        ),
    ]
