# Generated by Django 4.1.7 on 2023-05-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0020_alter_entretien_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="entretien",
            name="nom",
            field=models.CharField(default="Mise à jour", max_length=30),
        ),
    ]
