# Generated by Django 4.1.7 on 2023-05-14 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0021_entretien_nom"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructure",
            name="ip_reseau",
            field=models.CharField(
                default="192.168.0.0",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.?\\b){4}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="entretien",
            name="date",
            field=models.DateField(default="2023-05-14"),
        ),
    ]
