# Generated by Django 4.1.7 on 2023-05-14 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0022_infrastructure_ip_reseau_alter_entretien_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructure",
            name="masque",
            field=models.CharField(
                default="255.255.255.0",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?:128|192|224|240|248|252|254|255)\\.(?:0|128|192|224|240|248|252|254|255)\\.(?:0|128|192|224|240|248|252|254|255)\\.(?:0|128|192|224|240|248|252|254|255)$"
                    )
                ],
            ),
        ),
    ]
