# Generated by Django 4.1.7 on 2023-05-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RT_app", "0024_alter_infrastructure_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="nom",
            field=models.CharField(default="PC", max_length=30),
        ),
    ]
